<?php  
    if ($this->employe->get_Personne_noPersonne() != null) {
        if (!isset($_GET['rep'])) {
            echo "<div><p>Êtes-sur de vouloir supprimer cet employé ?</p>
                     <p>
                         <a class='enSavoirPlus' href='delpilote?rep=non&id=
                         ".$_GET['id']."'>Non </a>
                         <a class='enSavoirPlus' href='delpilote?rep=oui&id=
                         ".$_GET['id']."'>Oui</a>
                     </p>
                  </div>";
        }
    } else {
        echo "Employé inexistant<br />";
        echo "<a href='/ServDRH'>Retour</a>"; //Revoir la redirection vers la page gestpilote
    }
?>