<form action='' method='POST'>
    <center>
    <table>
        <tr>
            <td>
                <?php echo $this->element->nom->renderLabel(); ?>
            </td>
            <td>
                <?php echo $this->element->nom->renderViewHelper(); ?>
            </td>
        </tr>
        <tr>
            <td>
                <?php echo $this->element->prenom->renderLabel(); ?>
            </td>
            <td>
                <?php echo $this->element->prenom->renderViewHelper(); ?>
            </td>
        </tr>
        <tr>
            <td>
                <?php echo $this->element->prenom2->renderLabel(); ?>
            </td>
            <td>
                <?php echo $this->element->prenom2->renderViewHelper(); ?>
            </td>
        </tr>
        <tr>
            <td>
                <?php echo $this->element->prenom3->renderLabel(); ?>
            </td>
            <td>
                <?php echo $this->element->prenom3->renderViewHelper(); ?>
            </td>
        </tr>
        <tr>
            <td>
                <?php echo $this->element->dateNaissance->renderLabel(); ?>
            </td>
            <td>
                <?php echo $this->element->dateNaissance->renderViewHelper(); ?>
            </td>
        </tr>
        <tr>
            <td>
                <?php echo $this->element->noINSEE->renderLabel(); ?>
            </td>
            <td>
                <?php echo $this->element->noINSEE->renderViewHelper(); ?>
            </td>
        </tr>
        <tr>
            <td>
                <?php echo $this->element->numero->renderLabel(); ?>
            </td>
            <td>
                <?php echo $this->element->numero->renderViewHelper(); ?>
            </td>
        </tr>
        <tr>
            <td>
                <?php echo $this->element->labelAdresse->renderLabel(); ?>
            </td>
            <td>
                <?php echo $this->element->labelAdresse->renderViewHelper(); ?>
            </td>
        </tr>
        <tr>
            <td>
                <?php echo $this->element->immeuble->renderLabel(); ?>
            </td>
            <td>
                <?php echo $this->element->immeuble->renderViewHelper(); ?>
            </td>
        </tr>
        <tr>
            <td>
                <?php echo $this->element->etage->renderLabel(); ?>
            </td>
            <td>
                <?php echo $this->element->etage->renderViewHelper(); ?>
            </td>
        </tr>
        <tr>
            <td>
                <?php echo $this->element->porte->renderLabel(); ?>
            </td>
            <td>
                <?php echo $this->element->porte->renderViewHelper(); ?>
            </td>
        </tr>
        <tr>
            <td>
                <?php echo $this->element->cp->renderLabel(); ?>
            </td>
            <td>
                <?php echo $this->element->cp->renderViewHelper(); ?>
            </td>
        </tr>
        <tr>
            <td>
                <?php echo $this->element->etatProvince->renderLabel(); ?>
            </td>
            <td>
                <?php echo $this->element->etatProvince->renderViewHelper(); ?>
            </td>
        </tr>
        <tr>
            <td>
                <?php echo $this->element->ville->renderLabel(); ?>
            </td>
            <td>
                <?php echo $this->element->ville->renderViewHelper(); ?>
            </td>
        </tr>
        <tr>
            <td>
                <?php echo $this->element->pays->renderLabel(); ?>
            </td>
            <td>
                <?php echo $this->element->pays->renderViewHelper(); ?>
            </td>
        </tr>
        <tr>
            <td>
                <?php echo $this->element->email->renderLabel(); ?>
            </td>
            <td>
                <?php echo $this->element->email->renderViewHelper(); ?>
            </td>
        </tr>
        <tr>
            <td>
                <?php echo $this->element->role->renderLabel(); ?>
            </td>
            <td>
                <?php echo $this->element->role->renderViewHelper(); ?>
            </td>
        </tr>
        <tr>
            <td>
                <?php echo $this->element->labelMetier->renderLabel(); ?>
            </td>
            <td>
                <?php echo $this->element->labelMetier->renderViewHelper(); ?>
            </td>
        </tr>
        <tr>
            <td>
                <?php echo $this->element->password->renderLabel(); ?>
            </td>
            <td>
                <?php echo $this->element->password->renderViewHelper(); ?>
            </td>
        </tr>
        <tr>
            <td>
                <?php echo $this->element->passwordConfirm->renderLabel(); ?>
            </td>
            <td>
                <?php echo $this->element->passwordConfirm->renderViewHelper(); ?>
            </td>
        </tr>
        <tr>
            <td>
                <?php echo $this->element->habilitation->renderLabel(); ?>
            </td>
            <td>
                <?php echo $this->element->habilitation->renderViewHelper(); ?>
            </td>
        </tr>
    </table>
        <?php 
            echo $this->element->enregistrer->renderViewHelper();                            
            echo $this->element->annuler->renderViewHelper();
        ?>     
    </center>
</form>

