<center><h1>Service DRH-Gestion des pilotes </h1>
<?php
    echo "<p align=right><a class='enSavoirPlus' href='" . Zend_Registry::get('BaseUrl') .
                "/ServDRH/gestpilote/newpilote'>Ajouter un nouveau pilote</a></p>";
    if (!empty($this->AllPersonnes)) {
        echo "<table>";
        echo "<tr>
            <div class='sep'>
            <th>M&eacute;tier</th>
            <th>Nom</th>
            <th>Pr&eacute;nom</th>
            <th>Deuxième pr&eacute;nom</th>
            <th>Troisième pr&eacute;nom</th>
            <th>Date de naissance</th>
            <th>Num&eacute;ro INSEE</th>
            <th>Adresse</th>
            <th>Pays</th>
            <th>E-mail</th>
            <td></td>
            <td></td>
            <td></td>
            </div>
        </tr>";
        $i = 0;
        foreach ($this->AllPersonnes as $res){
            echo "<tr>
                <td> ". $this->ListeMetiers[$i]. "</td>
                <td>" . $res->get_nom(). "</td>
                <td>" . $res->get_prenom(). "</td>
                <td>" . $res->get_prenom2(). "</td>
                <td>" . $res->get_prenom3(). "</td>
                <td>" . $res->get_dateNaissance(). "</td>
                <td>" . $res->get_noINSEE(). "</td>
                <td>" . '' . "</td>
                <td>" . $res->get_labelPays(). "</td>
                <td>" . $res->get_email(). "</td>
                <td><a class='enSavoirPlus' href='" . Zend_Registry::get('BaseUrl') .
                "/ServDRH/gestpilote/updpilote?id=" . $res->get_noPersonne() . "'>Modifier</a></td>
                <td><a class='enSavoirPlus' href='" . Zend_Registry::get('BaseUrl') .
                "/ServDRH/gestpilote/congespilote?id=" . $res->get_noPersonne() . "'>Conges</a></td>
                <td><a class='enSavoirPlus' href='" . Zend_Registry::get('BaseUrl') .
                "/ServDRH/gestpilote/delpilote?id=" . $res->get_noPersonne() . "'>Supprimer</a></td>
                </tr>";
            $i++;
        }
        echo "</table>
              <p align='center'><a href='" . Zend_Registry::get('BaseUrl') .
                "/ServDRH'>Retour</a></p>";
    } else {
        echo "<br />
              <p align='center'>Aucun employé n'est enregistré</p>
              <p align='center'><a href='" . Zend_Registry::get('BaseUrl') .
                "/ServDRH'>Retour</a></p>";
    }
?>
