<center><h1>Modification d'une demande de congé</h1></center>

<?php
    if (!is_null($this->enregistrer)) {
        echo $this->enregistrer;
    } else {
        if (is_null($this->erreurInexistant)) {
            $messageErreur = $this->updForm->getMessages();
        
            if (!is_null($this->erreurDateDebutAnnee)) {
                echo $this->erreurDateDebutAnnee;
            }
            if (!is_null($this->erreurDateDebut)) {
                echo $this->erreurDateDebut;
            }
            if (!is_null($this->erreurDateFin)) {
                echo $this->erreurDateFin;
            }
            if (!is_null($this->erreurValidation)) {
                echo $this->erreurValidation;
            }
?>
            <form name="nouvel_employe" action="" method="post">
                <table>
                    <tr>
                        <td>
                        <?php 
                            echo "Date de début*"; 
                        ?>
                        </td>
                        <td>
                        <?php 
                            echo $this->updForm->jourDateDebut->renderViewHelper();
                            echo " / ";
                            echo $this->updForm->moisDateDebut->renderViewHelper();
                            echo " / ";
                            echo $this->updForm->anneeDateDebut->renderViewHelper();
                        ?>
                        </td>
                    </tr>
                    <tr>
                        <td>
                        <?php 
                            echo "Date de fin*"; 
                        ?>
                        </td>
                        <td>
                        <?php 
                            echo $this->updForm->jourDateFin->renderViewHelper();
                            echo " / ";
                            echo $this->updForm->moisDateFin->renderViewHelper();
                            echo " / ";
                            echo $this->updForm->anneeDateFin->renderViewHelper();
                        ?>
                        </td>
                    </tr>
                    <tr>
                        <td>
                        <?php 
                            echo $this->updForm->valider->renderLabel(); 
                        ?>
                        </td>
                        <td>
                        <?php 
                            echo $this->updForm->valider->renderViewHelper();
                        ?>
                        </td>
                    </tr>
                    <tr>
                        <td>
                        <?php 
                            echo $this->updForm->enAttente->renderLabel(); 
                        ?>
                        </td>
                        <td>
                        <?php 
                            echo $this->updForm->enAttente->renderViewHelper();
                        ?>
                        </td>
                    </tr>
                    <tr>
                        <td>
                        <?php 
                            echo $this->updForm->motif->renderLabel(); 
                        ?>
                        </td>
                        <td>
                        <?php 
                            echo $this->updForm->motif->renderViewHelper();
                            if (isset($messageErreur['motif']['isEmpty'])) {
                               echo "<br />".$messageErreur['motif']['isEmpty'];
                            }
                        ?>
                        </td>
                    </tr>
                    <tr>
                        <td>
                        <?php 
                            echo $this->updForm->labelTypeConge->renderLabel(); 
                        ?>
                        </td>
                        <td>
                        <?php 
                            echo $this->updForm->labelTypeConge->renderViewHelper();
                        ?>
                        </td>
                    </tr>
                    <tr>
                        <td>
                        <?php 
                            echo "Date de début d'année*"; 
                        ?>
                        </td>
                        <td>
                        <?php 
                            echo $this->updForm->jourDateDebutAnnee->renderViewHelper();
                            echo " / ";
                            echo $this->updForm->moisDateDebutAnnee->renderViewHelper();
                            echo " / ";
                            echo $this->updForm->anneeDateDebutAnnee->renderViewHelper();
                        ?>
                       </td>
                    </tr>            
                </table>
                <center>
                <?php
                    echo $this->updForm->enregistrer->renderViewHelper();
                    echo $this->updForm->annuler->renderViewHelper();            
                ?>
                </center>
            </form>
<?php
        } else {
            echo $this->erreurInexistant;
        }
    }
?>