<h1>Voulez vous vraiment suprimer cet aeroport?</h1>
<?php
if ($this->item) {
    echo "<table>
                <tr>
                    <td>Id</td>
                    <td>" . $this->item->get_noAeroport() . "</td>
                </tr>
                <tr>
                    <td>Label</td>
                    <td>" . $this->item->get_labelAeroport() . "</td>
                </tr>
                <tr>
                    <td>Ville</td>
                    <td>" . $this->item->get_labelVille() . "</td>
                </tr>
                <tr>
                    <td>Pays</td>
                    <td>" . $this->item->get_labelPays() . "</td>
                </tr>
            </table>";
    echo "<div><a class='enSavoirPlus' href='" . Zend_Registry::get('BaseUrl') .
                "/Aeroport/admin'>Non </a>
    <a class='enSavoirPlus' href='" . Zend_Registry::get('BaseUrl') .
                "/Aeroport/del?ok=ok&id=".$this->id."'>Oui</a></div>";
} else {
    echo "Ce Type d'incident n'existe pas dans la base de donnée!<br/><br/>
        <a class='enSavoirPlus'  href='" . Zend_Registry::get('BaseUrl') .
                "/ServExploitation/Typeincident/'>Retour</a><br/>";
}
?>