<h1>Aeroport N°<?php echo $this->id; ?></h1>


<?php
if ($this->item) {
    echo "<table>
                <tr>
                    <td>Id</td>
                    <td>" . $this->item->get_noAeroport() . "</td>
                </tr>
                <tr>
                    <td>Label</td>
                    <td>" . $this->item->get_labelAeroport() . "</td>
                </tr>
                <tr>
                    <td>Ville</td>
                    <td>" . $this->item->get_labelVille() . "</td>
                </tr>
                <tr>
                    <td>Pays</td>
                    <td>" . $this->item->get_labelPays() . "</td>
                </tr>
            </table>";
    echo "
        <a class='enSavoirPlus'  href='/Aeroport/upd?id=" . $this->id . "'>Modifier</a>
        <a class='enSavoirPlus'  href='/Aeroport/del?id=" . $this->id . "'>Supprimer</a><br/><br/>";
} else {
    echo "Cet Aéroport n'existe pas dans la base de donnée!<br/><br/>
        <a class='enSavoirPlus'  href='/Aeroport/admin/'>Retour</a><br/>";
}
?>