<div class="grid_16 sep">
    <h2>Service Planing</h2>
    <p class="prefix_1">Bienvenue !</p>
</div>
<div class="clear"></div>
<div class="prefix_1 grid_15">
    <ul>
        <li class="sep">
            Planification à S+4 :
            <a href="<?= Zend_Registry::get('BaseUrl'); ?>/ServPlaning/Planing" class="enSavoirPlus">Planing</a>
        </li>
        <li class="sep">
            Modification du planing entre S et S+3
            <a href="<?= Zend_Registry::get('BaseUrl'); ?>/ServPlaning/Modifplaning" class="enSavoirPlus">Modification du planing</a>
        </li>
    </ul>
    //
<!--    <table>         -->
            <?php
//            foreach ($this->listeMembres as $membre){
//                echo "<tr><td>";
//                    echo $membre->get_noPersonne();
//                echo "</td></tr>";
//            }
            ?>
<!--    </table>         -->
    <?php
//    echo $this->listeMembres;
    ?>
</div>