<h2>Administrateur</h2>
<h6>Bienvenue !</h6>
<div class="prefix_1">
    <ul>
        <li class="sep">Service DRH : <a href="<?= Zend_Registry::get('BaseUrl');
            ?>/ServDRH/" class="enSavoirPlus">-></a></li>
        <li class="sep">Service Commercial : <a href="<?= Zend_Registry::get('BaseUrl');
            ?>/ServCommercial/" class="enSavoirPlus">-></a></li>
        <li class="sep">Service Strategique : <a href="<?= Zend_Registry::get('BaseUrl');
            ?>/ServStrategique/" class="enSavoirPlus">-></a></li>
        <li class="sep">Service Exploitation : <a href="<?= Zend_Registry::get('BaseUrl');
            ?>/ServExploitation/" class="enSavoirPlus">-></a></li>
        <li class="sep">Service Planing : <a href="<?= Zend_Registry::get('BaseUrl');
            ?>/ServPlaning/" class="enSavoirPlus">-></a></li>
        <li class="sep">Service Maintenance : <a href="<?= Zend_Registry::get('BaseUrl');
            ?>/ServMaintenance/" class="enSavoirPlus">-></a></li>
        <li class="sep">Service Logistique : <a href="<?= Zend_Registry::get('BaseUrl');
            ?>/ServLogCom/" class="enSavoirPlus">-></a></li>
        <li class="sep">Service Agence : <a href="<?= Zend_Registry::get('BaseUrl');
            ?>/AgenceVoyage/" class="enSavoirPlus">-></a></li>
        
    </ul>
</div>
