<div class="grid_16 sep">
    <h2 style="display:inline;">Service Planing</h2>
    <h5 style="display:inline;"> - Planification à S+4</h5>
</div>
<div class="clear"></div>
<div class="prefix_1 grid_15">
    <h6 class="sep">Liste des Vols à planifier pour S+4 :</h6>
    <ul>
        <li class="sep">
            Planification des lignes journalières :
            <a href="/ServPlaning/Lignejournaliere" class="enSavoirPlus">Planifier</a>
        </li>
        <li class="sep">
            Planification des lignes hebdomadaires :
            <a href="/ServPlaning/Lignehebdomadaire" class="enSavoirPlus">Planifier</a>
        </li>
        <li class="sep">
            Planification des lignes mensuels :
            <a href="/ServPlaning/Lignemensuelle" class="enSavoirPlus">Planifier</a>
        </li>
        <li class="sep">
            Planification des lignes annuelles :
            <a href="/ServPlaning/Ligneannuelle" class="enSavoirPlus">Planifier</a>
        </li>
    </ul>
    <h6 class="sep">Modification : </h6>
    <ul>
        <li>
            Modification des vols planifiés pour la semaine S+4 :
            <a href="/ServPlaning/s4" class="enSavoirPlus">Modifier</a>
        </li>
    </ul>
</div>

