<div class="grid_16 sep">
    <h2 style="display:inline;">Service Planing</h2>
    <h5 style="display:inline;"> - Planification à S+4</h5>
</div>
<div class="clear"></div>
<div class="prefix_1 grid_15">
    <h6 class="sep">Liste des Vols à planifier pour S+4 :</h6>
    <ul>
        <li class="sep">
            Planification des lignes journalières :
            <a href="<?= Zend_Registry::get('BaseUrl'); ?>/ServPlaning/Lignejournaliere" class="enSavoirPlus">Planifier</a>
            <p>Il reste : <span class='aPlanifie'>
                <?= $this->nbPlanJourAFaire ?>
                </span> planification(s) à faire</p>
        </li>
        <li class="sep">
            Planification des lignes hebdomadaires :
            <a href="<?= Zend_Registry::get('BaseUrl'); ?>/ServPlaning/Lignehebdomadaire" class="enSavoirPlus">Planifier</a>
            <p>Il reste : <span class='aPlanifie'>
                <?= $this->nbPlanHebAFaire ?>
                </span> planification(s) à faire</p>
        </li>
        <li class="sep">
            Planification des lignes mensuels :
            <a href="<?= Zend_Registry::get('BaseUrl'); ?>/ServPlaning/Lignemensuelle" class="enSavoirPlus">Planifier</a>
            <p>Il reste : <span class='aPlanifie'>
                <?= $this->nbPlanMoisAFaire ?>
                </span> planification(s) à faire</p>
        </li>
        <li class="sep">
            Planification des lignes annuelles :
            <a href="<?= Zend_Registry::get('BaseUrl'); ?>/ServPlaning/Ligneannuelle" class="enSavoirPlus">Planifier</a>
            <p>Il reste : <span class='aPlanifie'>
                <?= $this->nbPlanAnnAFaire ?>
                </span> planification(s) à faire</p>
        </li>
    </ul>
    <h6 class="sep">Modification : </h6>
    <ul>
        <li>
            Modification des vols planifiés pour la semaine S+4 :
            <a href="<?= Zend_Registry::get('BaseUrl'); ?>/ServPlaning/s4" class="enSavoirPlus">Modifier</a>
        </li>
    </ul>
</div>

