<h1>Gestion des Agences</h1>
<?php
if ($this->all) {
    echo "<table>
            <tr>
                <th>Id</th>
                <th>Label</th>
                <th>Lancement</th>
                <th>Date de Cloture</th>
                <th>Extranet</th>
                <th>Adresse</th>
                <th></th>
                <th></th>
                <th></th>
            </tr>
            <tr>";
    foreach ($this->all as $val) {
        echo "<tr>
                <td>" . $val->get_noAgence() . "</td>
                <td>" . $val->get_labelAgence() . "</td>
                <td>" . $val->get_dateLancement() . "</td>";

        if ($val->get_dateCloture() != null)
            echo "<td>" . $val->get_dateCloture() . "</td>";
        else
            echo "<td>Actif</td>";

        if ($val->get_accesExtranet() == 1)
            echo "<td>Actif</td>";
        else
            echo "<td>Inactif</td>";

        echo "<td>" . $val->get_noAdresse() . "</td>";

        echo "  <td><a href='" . Zend_Registry::get('BaseUrl') .
                "/ServCommercial/Agence/detail?id=" . $val->get_noAgence() . "'>Detail</a></td>
                <td><a href='" . Zend_Registry::get('BaseUrl') .
                "/ServCommercial/Agence/upd?id=" . $val->get_noAgence() . "'>Modifier</a></td>
            </tr>";
    }
    echo "</table>";

} else {
    echo "<div>Il n'y a pas d'agence dans la base de donnée</div>";
}
echo "<br/><a class='enSavoirPlus' href='" . Zend_Registry::get('BaseUrl') .
                "/ServCommercial/Agence/new'>Ajouter</a>
    <a class='enSavoirPlus' href='" . Zend_Registry::get('BaseUrl') .
                "/ServCommercial/Agence/'>Retour</a>";