<h1>Agence N°<?php echo $this->id; ?></h1>
<?php echo $this->item; ?>
<br/><br/><br/><br/><br/><br/><br/>
<a class="enSavoirPlus" href='/ServCommercial/Agence/upd?id=<?php echo $this->id; ?>'>Modifier</a><br/><br/>
<a class="enSavoirPlus" href='/ServCommercial/Agence/del?id=<?php echo $this->id; ?>'>Supprimer</a><br/><br/>
<a class="enSavoirPlus" href='/ServCommercial/Agence/admin'>Retour</a><br/>