<div class="grid_16 alpha sep omega">
    <img src="<?= Zend_Registry::get('BaseUrl'); ?>/media/image/imgBaseCorps.jpg" />
</div>
<div class="clear sep"></div>
<div class="prefix_1 suffix_1 grid_14">
    <div class="alpha grid_4 suffix_1">
        <h1>Service</h1>
        <img class="sep"src="<?= Zend_Registry::get('BaseUrl'); ?>/media/image/vignette.jpg" />
        <p>
            Lorem ipsum dolor sit amet, consectetur adipiscing elit.
            Ut porttitor elit at sem mollis et pharetra arcu vulputate.
        </p>
    </div>
    <div class="grid_4 suffix_1">
        <h1>Environnement</h1>
        <img class="sep"src="<?= Zend_Registry::get('BaseUrl'); ?>/media/image/environnement.jpg" />
        <p>
            Lorem ipsum dolor sit amet, consectetur adipiscing elit.
            Ut porttitor elit at sem mollis et pharetra arcu vulputate.
        </p>
    </div>
    <div class="grid_4 omega">
        <h1>Disponibilite</h1>
        <img class="sep"src="<?= Zend_Registry::get('BaseUrl'); ?>/media/image/disponibilite.jpg" />
        <p>
            Lorem ipsum dolor sit amet, consectetur adipiscing elit.
            Ut porttitor elit at sem mollis et pharetra arcu vulputate.
        </p>
    </div>
</div>
<div class="clear sep"></div>

