<h1>Gestion des Places</h1>
<table>
    <tr>
        <td colspan="2"><a class="enSavoirPlus" href='/ServCommercial/Place/admin'>Admin</a>
            <a class="enSavoirPlus" href='/ServCommercial/Agence'>Gestion des Agences</a>
            <a class="enSavoirPlus" href='/ServCommercial/'>Retour</a>
        </td>
    </tr>
    <tr>
        <td><br/><img width="200" heigth="100" src="http://www.photo-libre.fr/transport/48.jpg"/></td>
        <td><br/><?php echo $this->all; ?></td>
    </tr>
</table>