<h1>Voulez vous vraiment suprimer cette reservation?</h1>

<?php
if ($this->item) {
    echo "<table>
                <tr>
                    <td width='50%'>Vol</td>
                    <td>" . $this->item->get_Vol_noVol() . "</td>
                </tr>
                <tr>
                    <td>Agence</td>
                    <td>" . $this->item->get_Agence_noAgence() . "</td>
                </tr>
                <tr>
                    <td>Nombre Reservation</td>
                    <td>" . $this->item->get_nbReservation() . "</td>
                </tr>
                <tr>
                    <td>Etat Traitement</td>
                    <td>";
    if ($this->item->get_enAttentedeTraitement()) {
        echo "Traité";
    } else {
        echo "Non traité";
    }
    echo "</td></tr><tr><td>Etat Validation</td><td>";
    if ($this->item->get_valider()) {
        echo "Validé";
    } else {
        echo "Non validé";
    }
    echo"</td>
                </tr>
            </table>";

    echo "<div><a class='enSavoirPlus' href='" . Zend_Registry::get('BaseUrl') .
                "/ServCommercial/Reservation/admin'>Non </a>
          <a class='enSavoirPlus' href='" . Zend_Registry::get('BaseUrl') .
                "/ServCommercial/Reservation/del?ok=ok&id=" . $this->id . "'>Oui</a></div>";
} else {
    echo "Cette Agence n'existe pas dans la base de donnée!<br/><br/>
        <div><a class='enSavoirPlus' href='" . Zend_Registry::get('BaseUrl') .
                "/ServCommercial/Reservation/admin'>Retour </a>";
}