<h1>Reservation N°<?php echo $this->id; ?></h1>

<?php
if ($this->item) {
    echo "<table>
                <tr>
                    <td width='50%'>Vol</td>
                    <td>" . $this->item->get_Vol_noVol() . "</td>
                </tr>
                <tr>
                    <td>Agence</td>
                    <td>" . $this->item->get_Agence_noAgence() . "</td>
                </tr>
                <tr>
                    <td>Nombre Reservation</td>
                    <td>" . $this->item->get_nbReservation() . "</td>
                </tr>
                <tr>
                    <td>Etat Traitement</td>
                    <td>";
    if ($this->item->get_enAttentedeTraitement()) {
        echo "Traité";
    } else {
        echo "Non traité";
    }
    echo "</td></tr><tr><td>Etat Validation</td><td>";
    if ($this->item->get_valider()) {
        echo "Validé";
    } else {
        echo "Non validé";
    }
    echo"</td>
                </tr>                
            </table>";

    echo "<center><a class='enSavoirPlus' href='/ServCommercial/Reservation/upd?id=" . $this->id . "'>Modifier</a>";
} else {
    echo "Cette Agence n'existe pas dans la base de donnée!<center>";
}
?>
<a class='enSavoirPlus' href='/ServCommercial/Reservation/admin'>Retour</a></center>