<h1>Place N°<?php echo $this->id; ?></h1>
<?php echo $this->item; ?>
<a class="enSavoirPlus" href='/ServCommercial/Reservation/upd?id[]=<?php echo $this->id0; ?>&id[]=<?php echo $this->id1; ?>'>Modifier</a><br/><br/>
<a class="enSavoirPlus" href='/ServCommercial/Reservation/del?id[]=<?php echo $this->id0; ?>&id[]=<?php echo $this->id1; ?>'>Supprimer</a><br/><br/>
<a class="enSavoirPlus" href='/ServCommercial/Reservation/admin'>Retour</a><br/>