<h1>Gestion des Demande de reservation</h1>
<table>
    <tr>
        <td colspan="2"><a class="enSavoirPlus" href='/ServCommercial/Reservation/admin'>Admin</a> 
            <a class="enSavoirPlus" href='/ServCommercial/'>Retour</a>
        </td>
    </tr>
    <tr>
        <td><br/><img width="200" heigth="100" src="http://www.photo-libre.fr/business/3.jpg"/></td>
        <td><br/><?php echo $this->all; ?></td>
    </tr>
</table>