<h1>Gestion des Demande de reservation</h1>

<?php
if ($this->all) {
    echo "<table>
                <tr>
                    <th>Vol</th>
                    <th>Agence</th>
                    <th>Nombre de place</th>
                    <th>Traitement</th>
                    <th>Validation</th>
                    <th>Date du post</th>
                </tr>\n";
    foreach ($this->all as $val) {
        $dateExplode = explode("-", $val->get_heurePost());
        $heureExplode = explode(" ", $dateExplode[2]);
        $dateExplode[2] = $heureExplode[0];
        $heureExplode = explode(":", $heureExplode[1]);
        if ((time() - mktime($heureExplode[0], $heureExplode[1], $heureExplode[2]
                        , $dateExplode[1], $dateExplode[2], $dateExplode[0])) > 7200) {
            echo "<tr><td>" . $val->get_Vol_noVol() . "</td>
                    <td>" . $val->get_Agence_noAgence() . "</td>
                    <td>" . $val->get_nbReservation() . "</td>
                    <td>";
            if ($val->get_enAttentedeTraitement()) {
                echo "Traité";
            } else {
                echo "Non traité";
            }
            echo "</td><td>";
            if ($val->get_valider()) {
                echo "Validé";
            } else {
                echo "Non validé";
            }
            echo"</td><td>" . $val->get_heurePost() . "</td></tr>\n";
        }
    }
    echo "</table>";
} else {
    echo "<div>Il n'y a pas de reservation confirmée dans la base de donnée</div>";
}
?>
<center>
    <a class='enSavoirPlus' href='<?= Zend_Registry::get('BaseUrl'); ?>/ServCommercial/Reservation/admin'>Admin</a>
    <a class='enSavoirPlus' href='<?= Zend_Registry::get('BaseUrl'); ?>/ServCommercial/'>Retour</a><br/><br/>
    <img width="200" heigth="100" src="http://www.photo-libre.fr/business/3.jpg"/>
</center>