<h1>Menu N°<?php echo $this->id; ?></h1>
<?php
if ($this->item) {
    echo "<table>
                <tr>
                    <td>Id</td>
                    <td>" . $this->item->get_idMenu() . "</td>
                </tr>
                <tr>
                    <td>Label</td>
                    <td>" . $this->item->get_labelMenu() . "</td>
                </tr>";
    if ($this->tab) {
        foreach ($this->tab as $key => $val) {
            echo "<tr>";
            if($key == 0)
                echo "<td>Regime Alimentaire</td>";
            else
                echo "<td></td>";
            echo "<td>" . $val . "</td>
                  </tr>";
        }
    }
    echo "</table>";

    echo "<a class='enSavoirPlus' href='" . Zend_Registry::get('BaseUrl') .
                "/ServLogCom/Menu/upd?id=" . $this->id . "'>Modifier</a>
          <a class='enSavoirPlus' href='" . Zend_Registry::get('BaseUrl') .
                "/ServLogCom/Menu/del?id=" . $this->id . "'>Supprimer</a>
          <a class='enSavoirPlus' href='" . Zend_Registry::get('BaseUrl') .
                "/ServLogCom/Menu/admin'>Retour</a>";
} else {
    echo "Ce Menu n'existe pas dans la base de donnée! <br/><br/>";
}
?>