<h1>Voulez vous vraiment suprimer ce Regime Alimentaire?</h1>

<?php
if ($this->item) {
    echo "<table>
                <tr>
                    <td>Id</td>
                    <td>" . $this->item->get_noRegimeAlimentaire() . "</td>
                </tr>
                <tr>
                    <td>Label</td>
                    <td>" . $this->item->get_labelRegimeAlimentaire() . "</td>
                </tr>
            </table>";

    echo "<div><a class='enSavoirPlus' href='" . Zend_Registry::get('BaseUrl') .
                "/ServLogCom/Regimealimentaire/admin'>Non </a>
          <a class='enSavoirPlus' href='" . Zend_Registry::get('BaseUrl') .
                "/ServLogCom/Regimealimentaire/del?ok=ok&id=" . $this->id . "'>Oui</a></div>";
} else {
    echo "Cette Agence n'existe pas dans la base de donnée!<br/><br/>";
}