<div>
    <h1 style='display: inline;'>Service Maintenance - </h1>
    <h3 style='display: inline;'>Gestion des Types de Maintenance - </h3>
    <h5 style='display: inline;'>Affichage par Modèle </h5>
    </br></br></br>
    <div style="margin-bottom: 30px;">
        <?php
        if ( count( ServMaintenance_Model_Modele::getAll() ) > 0 ) {
            echo "<a class='enSavoirPlus' href='" . Zend_Registry::get( 'BaseUrl' ) .
            "/ServMaintenance/Gesttypemaintenance/Newtypemaintenance'>Ajouter un type de Maintenance</a>";
        } else {
            echo '<a href="' . Zend_Registry::get( 'BaseUrl' ) .
            '/ServMaintenance/Gestmodele" class="enSavoirPlusUrg">Pour Ajouter un type de Maintenance, ajouter d\'abord un modèle !</a>';
        }
        ?>
    </div>
    <div>
        <?php
        if (
            isset( $this->ListeModeles ) && is_array( $this->ListeModeles ) &&
            isset( $this->ListeTypesMaintenance ) && is_array( $this->ListeTypesMaintenance ) &&
            isset( $this->ListeConstructeur ) && is_array( $this->ListeConstructeur )
        ) {
            foreach ( $this->ListeModeles as $noModele => $modele ) {
                echo'<table>';
                if ( $modele instanceof ServMaintenance_Model_Modele ) {
                    if (
                        isset( $this->ListeConstructeur[ $modele->get_noConstructeur() ] ) &&
                        $this->ListeConstructeur[ $modele->get_noConstructeur() ] instanceof ServMaintenance_Model_Constructeur
                    ) {

                        echo '<tr><th colspan="5" style="border-bottom: #777 1px solid; background-color: #fec380;"><h6>' . $modele->get_noModele() .
                        ' - ' . $modele->get_label() . ' - ' .
                        $this->ListeConstructeur[ $modele->get_noConstructeur() ]->get_label() . '</h6></th>';

                        if ( isset( $this->ListeTypesMaintenance[ $noModele ] ) && count( $this->ListeTypesMaintenance[ $noModele ] ) > 0 ) {
                            echo '
                              <tr>
                                <th>No.</th>
                                <th>Appellation</th>
                                <th>Duree Minimum</th>
                                <th>Interval en nombre d\'Heure de Vol</th>
                                <th></th>
                              </tr>
                            ';
                            foreach ( $this->ListeTypesMaintenance[ $noModele ] as $TypeMaintenance ) {
                                if ( $TypeMaintenance instanceof ServMaintenance_Model_TypeMaintenance ) {
                                    echo '<tr>
                                        <td>' . $TypeMaintenance->get_noTypeMaintenance() . '</td>
                                        <td>' . $TypeMaintenance->get_label() . '</td>
                                        <td>' . $TypeMaintenance->get_dureeMaintenance() . '</td>
                                        <td>' . $TypeMaintenance->get_periode() . '</td>
                                        <td><a class="enSavoirPlus" href="' . Zend_Registry::get( 'BaseUrl' ) .
                                    '/ServMaintenance/Gesttypemaintenance/Updtypemaintenance/noTypeMaintenance/' . $TypeMaintenance->get_noTypeMaintenance() . '">Modifier</a></td>
                                    </tr>';
                                }
                            }
                        } else {
                            echo '<tr><td colspan="">Aucun Type de Maintenance enregistré pour ce modèle</td></tr>';
                        }
                    }
                    echo '<tr style="background-color: #eee;"><td colspan="5"><a class="enSavoirPlus" href="' . Zend_Registry::get( 'BaseUrl' ) .
                    '/ServMaintenance/Gesttypemaintenance/Newtypemaintenance/noModele/' . $noModele . '">Ajouter un Type de Maintenance pour ce modèle</a></br></td></tr>';
                }
                echo '</table></br>';
            }
        }
        ?>
    </div>
</div>