<?php echo $this->doctype( 'HTML5' ) . PHP_EOL; ?>
<html>
    <head>
        <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
        <?php
        //Affichage style
        $this->headLink()->appendStylesheet( '/ressource/css/main.css' );
        echo $this->headLink() . PHP_EOL;
        //Affichage du titre
        echo $this->headTitle() . PHP_EOL;
        //affichage des scripts js (si il y en a)
        echo $this->headScript() . PHP_EOL;
        ?>
    </head>
    <body>
        <div id="wrap">
            <div id='head' class="sep">
                <div id="menu">
                    <?php echo $this->placeholder( 'sidebar' ); ?>
                </div>
                <div id="login">
                    <?php echo $this->placeholder( 'login' ); ?>
                </div>
            </div>
            <div class="container_16 sep tweakfoot" id="main" style="min-height: 400px; margin-top: 10px;">
                <?php echo $this->layout()->content; ?>
            </div>
        </div>
        <div id='footer'>
            <div id='footer-content'>
                <p><a>Terms of Use</a>|<a>XHTML</a>|<a>CSS</a><br />
                    Copyright © Gr3Insset<br />
                    Design by Gr3Insset</p>
            </div>
            <div id='footer-log'>
                <?php Spesx_Log::GetLogHtml(); ?>
            </div>
        </div>
    </body>
</html>