<div>
    <h1 style='display: inline;'>Service Maintenance - </h1><h3 style='display: inline;'>Gestion du Parc d'Appareils - </h3>
    </br></br></br>
    <h3 style='display: inline; margin-right: 50px;'>Liste des Appareils</h3>
    <a class="enSavoirPlus" style='display: inline;' href='/ServMaintenance/Gestappareil/Affavionenservice'>En Service</a>-
    <a class="enSavoirPlus" style='display: inline;' href='/ServMaintenance/Gestappareil/Affavionall'>Tous</a>-
    <a class="enSavoirPlus" style='display: inline;' href='/ServMaintenance/Gestappareil/Affavionhorsservice'>Hors Service</a>
    <br/><br/><br/>
    <a class='enSavoirPlus' href='/ServMaintenance/Gestappareil/Newappareil'>Ajouter un Appareil</a>
    <br/><br/><br/>
    <a class='enSavoirPlus'  href=''>Mise Hors Service Planifié (Supérieur à 4 Semaines)</a>
    <br/><br/>

    <a class='enSavoirPlusUrg'  href=''>Mise Hors Service Urgente (Inférieur à 4 Semaines)</a>
    <br/><br/>
    <p>
        Attention !! la mise Hors-Service d'un appreil entrainera des complications pour 
        le Service Planning.
    </p>
    <br/>

</div>