<div>
    <h1 style='display: inline;'>Service Maintenance - </h1>
    <h3 style='display: inline;'>Gestion du Parc d'Appareils - </h3>
    <h5 style='display: inline'>Ajout d'un Appareil</h5>
    </br></br></br>
    <div>
        <?php if (isset($this->message)) {
            echo '<h3>'.$this->message.'</h3>';
        } ?>
    </div>
    <div>
        <?php
        if (isset($this->form)) {
            echo $this->form;
        }
        ?>
    </div>
</div>