<div>
    <h1 style='display: inline;'>Service Maintenance - </h1>
    <h3 style='display: inline;'>Gestion des Tâches de Maintenance - </h3><br/>
    <h5 style='display: inline;'>Planification d'une Maintenance <?php if (isset($this->label)) {
    echo $this->label;
} ?></h5>
    </br></br></br>
    <?php
    if (isset($this->message)) {
        echo $this->message;
    }
    if (isset($this->form)) {
        echo $this->form;
    }
    ?>
</div>