<div>
    <h1 style='display: inline;'>Service Maintenance - </h1>
    <h3 style='display: inline;'>Gestion des Tâches de Maintenance - </h3>
    </br></br></br>
    
    <div>
        <h6>Tâche(s) en cours:</h6>
        <p style="margin-left: 30px;">
            <span style="color: green"><?php echo'x'; ?> Maintenance(s) Préventive(s) </span><br/>
            <span style="color: red"><?php echo 'x'; ?> Maintenance(s) Urgente(s)</span><br/>
            
            <br/><a style="margin-left: 30px;" class="enSavoirPlus">Voir</a><br/><br/>
        </p>
    </div>
    <div>
        <h6>Tâche(s) pour (s à s+4):</h6>
        <p style="margin-left: 30px;">
            <span style="color: green"><?php echo 'x'; ?> Maintenance(s) Préventive(s) Planifiée(s)</span>
            </br>
            <span style="color: orange"><?php echo 'x'; ?> Maintenance(s) Urgente(s) Planifiée(s)</span>
            </br>
            <span style="color: red"><?php echo 'x'; ?> Maintenance(s) Urgente(s) à Planifiée(s)</span>
            </br>
            <br/><a style="margin-left: 30px;" class="enSavoirPlus">Planifier</a> (Risque d'entraîner des Interruptions de Service)<br/><br/>
        </p>
    </div>
    <div>
        <h6>Tâche(s) pour (s+5 à s+8):</h6>
        <p style="margin-left: 30px;">
            <span style="color: green"><?php echo 'x'; ?> Maintenance(s) Préventive(s) Planifiée(s)</span>
            </br>
            <span style="color: orange"><?php echo 'x'; ?> Maintenance(s) Urgente(s) Planifiée(s)</span>
            </br>
            <span style="color: red"><?php echo 'x'; ?> Maintenance(s) Urgente(s) à Planifiée(s)</span>
            </br>
            <br/><a style="margin-left: 30px;" class="enSavoirPlus">Planifier</a><br/><br/>
        </p>
    </div>
    
</div> 