<div>
    <h1 style='display: inline;'>Service Maintenance - </h1>
    <h3 style='display: inline;'>Gestion des Tâches de Maintenance - </h3>
    </br></br></br>
    
    <div>
        <h6>Tâche(s) en cours: <?php echo'x'; ?> Maintenance(s)</h6>

    </div>
    <div>
        <h6>Tâche(s) Planifiée(s) débutant pour (s à s+4): <?php echo'x'; ?> Maintenance(s)</h6>
    </div>
    <div>
        <h6>Tâche(s) à Planifiée(s) débutant pour (s+5 à s+8): <?php echo'x'; ?> Maintenance(s)</h6>
    </div>
    
</div> 