

<div>
    <p>Service Maintenance:</p>
    <ul>
        <li><a href='<?php $this->baseUrl(); ?>/ServMaintenance/Gestappareil'>Afficher les Avions</a></li>
        <li><a href='<?php $this->baseUrl(); ?>/ServMaintenance/Gestmodele'>Afficher les Modeles</a></li>
        <li><a href='<?php $this->baseUrl(); ?>/ServMaintenance/Gestconstructeur'>Afficher les Constructeurs</a></li>
        <li><a href='<?php $this->baseUrl(); ?>/ServMaintenance/index/aplanifier'>Afficher les Avions à planifier</a></li>
        <li><a href='<?php $this->baseUrl(); ?>/ServMaintenance/Gesttypemaintenance'>Afficher les Tâches planifiés</a></li>
    </ul>
</div>