<div>
    <h1>Service Maintenance - </h1>
    <br/>
        <a href='<?= Zend_Registry::get('BaseUrl'); ?>/ServMaintenance/Gestappareil'><h3>Gestion du Parc d'Appareils</h3></a></br>
        </br>
        <a href='<?= Zend_Registry::get('BaseUrl'); ?>/ServMaintenance/Gesttachemaintenance'><h3>Gestion des Tâches de Maintenance</h3></a></br>
        <a href='<?= Zend_Registry::get('BaseUrl'); ?>/ServMaintenance/Gesttypemaintenance'><h3>Gestion des Types de Maintenance</h3></a></br>
        </br>
        <a href='<?= Zend_Registry::get('BaseUrl'); ?>/ServMaintenance/Gestmodele'><h3>Gestion des Modeles</h3></a></br>
        <a href='<?= Zend_Registry::get('BaseUrl'); ?>/ServMaintenance/Gestconstructeur'><h3>Gestion des Constructeurs</h3></a></br>
</div>