<div>
    <h1>Service Maintenance - </h1>
    <br/>
        <a href='<?php $this->baseUrl(); ?>/ServMaintenance/Gestappareil'><h3>Gestion des Appareils</h3></a></br>
        </br>
        <a href='<?php $this->baseUrl(); ?>/ServMaintenance/Gesttypemaintenance'><h3>Gestion des Types des Maintenances</h3></a></br>
        </br>
        <a href='<?php $this->baseUrl(); ?>/ServMaintenance/Gestmodele'><h3>Gestion des Modeles</h3></a></br>
        <a href='<?php $this->baseUrl(); ?>/ServMaintenance/Gestconstructeur'><h3>Gestion des Constructeurs</h3></a></br>
</div>