<div class="grid_16 sep">
    <h2 style="display:inline;">Service Planing</h2>
    <h5 style="display:inline;"> - Modification de planification à S et S+3</h5>
</div>
<div class="clear"></div>
<div class="prefix_1 grid_15">
    <h6 class="sep">Modification des planifications :</h6>
    <ul>
        <li class="sep">
            à semaine S :
            <a href="/ServPlaning/s" class="enSavoirPlus">Modification</a>
        </li>
        <li class="sep">
            à semaine S+1 :
            <a href="/ServPlaning/s1" class="enSavoirPlus">Modification</a>
        </li>
        <li class="sep">
            à semaine S+2 :
            <a href="/ServPlaning/s2" class="enSavoirPlus">Modification</a>
        </li>
        <li class="sep">
            à semaine S+3 :
            <a href="/ServPlaning/s3" class="enSavoirPlus">Modification</a>
        </li>
    </ul>
</div>

