<div class="grid_6 sep">
    <h2>
        Changement d'Email
    </h2>
    <h6>
        <?php
            echo $this->personne->get_prenom() . ' ' . $this->personne->get_nom();
        ?>
    </h6>
    <p class="red">
        ATTENTION : Changer d'email revient à changer de login, et cela
        dès la validation du formulaire !"
    </p>
</div>
<div class="clear"></div>
<div class="prefix_1 ">
    <?php
        if(!empty($_POST) && isset($this->errorMessage)){
            echo "<p class='red'>" . $this->errorMessage . "</p>";
        }
    echo $this->changeEmailForm->render();
    ?>
</div>