<div class="grid_6 sep">
    <h2>
        Modificatoin du telephone
    </h2>
    <h6>
        <?php
            echo $this->personne->get_prenom() . ' ' . $this->personne->get_nom();
        ?>
    </h6>

</div>
<div class="clear"></div>
<div class="prefix_1 ">
    <?php
        if(!empty($_POST) && isset($this->errorMessage)){
            echo "<p class='red'>" . $this->errorMessage . "</p>";
        }
    echo $this->changeTelephoneForm->render();
    ?>
</div>