<?php
//var_dump($this->personne);
//var_dump($this->adresse);
//var_dump($this->telephone);
?>
<div class="grid_16 sep">
    <h2>Profil :</h2>
</div>
<div class="clear"></div>
<div class="grid_15 prefix_1">
    <p class="sep">
        <?php
        //construction de la chaine $identite
        $identite = $this->personne->get_nom() . ' ' . $this->personne->get_prenom();
        if ($this->personne->get_prenom2() !== null) {
            $identite = $identite . ' ' . $this->personne->get_prenom2();
            if ($this->personne->get_prenom3() !== null) {
                $identite = $identite . ' ' . $this->personne->get_prenom3();
            }
        }
        //affichage
        echo 'Identité : <span class="bold">' . $identite . '</span>';
        ?>
    </p>
    <p class="sep">
        <?php
        $dateNaissance = new DateTime($this->personne->get_dateNaissance());
        echo 'Date de Naissance : <span class="bold">' . $dateNaissance->format('d/m/Y') . '</span>';
        ?>
    </p>
    <p class="sep">
        <?php
        echo 'Numéro de sécurité sociale : <span class="bold">' . $this->personne->get_noINSEE() . '</span>';
        ?>
    </p>
    <div class="alpha grid_6 sep">
        <p>
            <?php
            echo 'Email de contact : <span class="bold">' . $this->personne->get_email() . '</span>';
            ?>
        </p>
    </div>
    <div class="grid_3">
        <p>
            <?php
            echo '<a href="/utilisateur/modifEmail" class="enSavoirPlus">Modifier le mail</a>';
            ?>
        </p>
    </div>
    <div class="clear">

    </div>
    <div class="alpha grid_6 sep">
        <p>
            <?php
            $adresse = $this->adresse->get_numero() . ', ' . $this->adresse->get_adresse();
            $option = null;
            if ($this->adresse->get_porte() !== null) {
                $option .= 'porte ' . $this->adresse->get_porte() . ', ';
            }
            if ($this->adresse->get_etage() !== null) {
                $option .= 'etage ' . $this->adresse->get_etage() . ', ';
            }
            if ($this->adresse->get_immeuble() !== null) {
                $option .= 'immeuble ' . $this->adresse->get_immeuble() . ', ';
            }
            $region = $this->adresse->get_codepostal() . ' ' .
                $this->adresse->get_labelVille() . ' ' .
                $this->adresse->get_labelPays();
            if ($option !== null) {
                $adresseTotale = $option . '<br/>' . $adresse . '<br />' . $region;
            } else {
                $adresseTotale = $adresse . '<br />' . $region;
            }
            echo 'Adresse : <br /><span class="bold">' . $adresseTotale . '</span>';
            ?>
        </p>
    </div>
    <div class="grid_3">
        <p>
            <?php
            echo '<a class="enSavoirPlus" href="/utilisateur/modifAdresse">Modifier l\'adresse</a>';
            ?>
        </p>
    </div>
    <div class="clear"></div>
    <div class="grid_12 alpha omega sep">
        <?php
        foreach ($this->telephones as $tel) {
            echo '<div class="grid_6 sep alpha">';
                echo '<p>';
                echo 'Telephone : <span class="bold">' .
                    $tel->get_labelTelephone() .
                    ' : ' .
                    $tel->get_numTelephone() . '</span><br/>';
                echo '</p>';
            echo '</div>';
            echo '<div class="grid_6 omega">';
                echo '<a href="/utilisateur/modifTelephone/id/' .
                    $tel->get_noTelephone() .
                    '" class="enSavoirPlus">Modifier</a>';
                echo '<a href="/utilisateur/deleteTelephone/id/' .
                    $tel->get_noTelephone() .
                    '" class="enSavoirPlus">Supprimer</a>';
                    //Version POST (non fonctionnel, probleme des boutons submit
//                echo '<form action="/utilisateur/mod_telephone" method="POST">';
//                    echo '<input type="hidden" name="mode" value="mod" />';
//                    echo '<input type="hidden" name="id" value="' .
//                        $tel->get_noTelephone() .
//                        '" />';
//                    echo '<input type="submit" class="enSavoirPlus" value="modifier"/>';
//                echo '</form>';
//                echo '<form action="/utilisateur/mod_telephone" method="POST">';
//                    echo '<input type="hidden" name="mode" value="rm" />';
//                    echo '<input type="hidden" name="id" value="' .
//                        $tel->get_noTelephone() .
//                        '" />';
//                    echo '<input type="hidden" name="idPers" value="' .
//                        $tel->get_noPersonne() .
//                        '"/>';
//                    echo '<input type="submit" class="enSavoirPlus" value="supprimer"/>';
//                echo '</form>';
            echo '</div>';
            echo '<div class="clear"></div>';
        }
        ?>
    </div>
    <div class="clear"></div>
    <div class="grid_6 prefix_6 alpha omega">
        <!--
        <form action="/utilisateur/mod_telephone" method="POST">
            <input type="hidden" name="mode" value="add" />
            <input type="hidden" name="id" value="
            <?php //echo $tel->get_noPersonne(); ?>" />
            <input type="submit" value="ajouter un telphone" />
        </form>
        -->
        <a href="/utilisateur/addTelephone" class="enSavoirPlus">ajouter un Telephone</a>
    </div>
    <div class="clear"></div>
</div>
<div class="clear"></div>