<h1>Service Commercial</h1>
<table>
    <tr>
        <td width="50%">
            <img style="margin-right:50px" width="200" height="130" src="http://www.photo-libre.fr/business/146a.jpg"/>
            </td>
        <td>
            <div><a class="enSavoirPlus" href="<?= Zend_Registry::get('BaseUrl');
                ?>/ServCommercial/Reservation/">Demandes de réservations</a></div></br>
            <div><a class="enSavoirPlus" href="<?= Zend_Registry::get('BaseUrl');
                ?>/ServCommercial/Place/">Places réservées</a></div>
        </td>
    </tr>
</table>



