<?php $this->placeholder('login')->captureStart();
if (Zend_Auth::getInstance()->hasIdentity()): ?>
    
    <a href="http://<?php echo $this->baseUrl(); echo 'local.inssetairlines';?>/auth/deconnection"><?php echo Zend_Auth::getInstance()->getIdentity(); ?></a>
<?php else: ?>
    <a href="http://<?php echo $this->baseUrl(); echo 'local.inssetairlines';?>/auth/login">Connexion</a>
<?php endif;
$this->placeholder('login')->captureEnd(); ?>