<?php $this->placeholder('login')->captureStart(); ?>
<?php if (Zend_Auth::getInstance()->hasIdentity()): ?>

    <a href="<?= Zend_Registry::get('BaseUrl'); ?>/auth/redirection"><img src="<?= Zend_Registry::get('BaseUrl'); ?>/media/image/lock.png" /></a>

<?php else: ?>
    <a href="<?= Zend_Registry::get('BaseUrl'); ?>/auth/login"><img src="<?= Zend_Registry::get('BaseUrl'); ?>/media/image/lock.png" /></a>
<?php endif; ?>

<?php $this->placeholder('login')->captureEnd(); ?>
