<?php $this->placeholder( 'login' )->captureStart(); ?>


<?php if ( Zend_Auth::getInstance()->hasIdentity() ): ?>
    <ul>
        <li>
            <a href="#"><img src="/media/image/lock.png" /></a>
            <ul class="sousLogin">
                <li><p><?php echo Zend_Auth::getInstance()->getIdentity(); ?></p></li>
                <hr/>
                <li><a href="/utilisateur/profil">Gestion du profil</a></li>
                <li><a href="/utilisateur/modifMdp">Changer le Mot de Passe</a></li>
                <li> <a href="/auth/deconnection">Déconnection</a></li>
            </ul>
        </li>
    </ul>
<?php else: ?>
    <a href="/auth/login"><img src="/media/image/lock.png" /></a>
<?php endif; ?>

<?php $this->placeholder( 'login' )->captureEnd(); ?>
