<div class="grid_16 sep">
    <h2 style="display:inline;">Service Planing</h2>
    <h5 style="display:inline;"> - Planification S+4, annuelle</h5>
    <h6>Nombre de jours avant la fin de l'annee : <span class="red"><?= $this->nbrJourAvantFinAnnee; ?></span></h6>
</div>
<div class="clear"></div>
<div class="prefix_1 grid_15">
    <?php
    if ($this->derniereSemaine) {
        echo "<p class='red'>Attention : La semaine actuelle est la derniere semaine de l'année,
            les planifications affichées sont obligatoires !</p>";
    } else {
        echo "<p class='red'>Attention : la planification de ces recurences ne sont pas forcement obligatoire,
        mais doivent être planifié avant la fin de l'année</p>";
    }
    ?>

    <table>
        <tr>
            <th style='min-width:300px;'>Ligne</th>
            <th>Nombre de vol à planifier</th>
            <td></td>
        </tr>
        <tr>
            <?php
            if (isset($this->listeAnn) && is_array($this->listeAnn) && count($this->listeAnn) > 0) {
                foreach ($this->listeAnn as $key => $value) {

                    echo '<td>';
                    echo $value['label'];
                    echo '</td>';
                    echo '<td>';
                    echo $value['recurence'];
                    echo '</td>';
                    echo '<td>';
                    echo '<a href="' . Zend_Controller_Front::getInstance()->getBaseUrl() .
                    '/ServPlaning/Ligneannuelle/addplanification/id/' .
                    $key .
                    '" class="enSavoirPlus">Planifier</a>';
                    echo '</td>';
                }
            } else {
                echo '<td colspan="2">Aucun Vol à planifier</td>';
            }
            ?>
        </tr>
    </table>
</div>