<h1>Commande N°<?php echo $this->id; ?></h1>
<?php
if ($this->item) {
    echo "<table>
                <tr>
                    <td>Id</td>
                    <td>" . $this->item->get_noCommandeNourriture() . "</td>
                </tr>
                <tr>
                    <td>Date de livraison</td>
                    <td>" . $this->item->get_dateLivraison() . "</td>
                </tr>
                <tr>
                    <td>Date de Commande</td>
                    <td>" . $this->item->get_dateCommande() . "</td>
                </tr>
                <tr>
                    <td>Aeroport de livraison</td>
                    <td>" . $this->item->get_labelAeroportLivraison() . "</td>
                </tr>
            </table>";
    
    echo "<a class='enSavoirPlus' href='/ServLogCom/Commandenourriture/upd?id=". $this->id ."'>Modifier</a>
          <a class='enSavoirPlus' href='/ServLogCom/Commandenourriture/del?id=". $this->id ."'>Supprimer</a>
          <a class='enSavoirPlus' href='/ServLogCom/Commandenourriture/admin'>Retour</a>";
} else {
    echo "Cette commande n'existe pas dans la base de donnée! <br/><br/>
        <a class='enSavoirPlus' href='/ServLogCom/Commandenourriture/admin'>Retour</a>";
}

?>